USE [db_SQLCaseStudies]

SELECT * FROM DIM_CUSTOMER
SELECT * FROM DIM_DATE
SELECT * FROM DIM_LOCATION
SELECT * FROM DIM_MANUFACTURER
SELECT * FROM DIM_MODEL
SELECT * FROM FACT_TRANSACTIONS

/*************************** QUESTIONS FROM RETAIL DATA ANALYSIS **********************************/

--Q1.
SELECT DISTINCT
State
FROM
FACT_TRANSACTIONS AS T1
INNER JOIN DIM_LOCATION AS T2 ON T2.IDLocation = T1.IDLocation
WHERE
Date > '2004-12-31'

--Q2.
SELECT TOP 1
STATE
FROM
(SELECT
Manufacturer_Name,
Quantity,
IDLocation 
FROM
DIM_MODEL AS T1
INNER JOIN FACT_TRANSACTIONS AS T2 ON T2.IDModel = T1.IDModel
INNER JOIN DIM_MANUFACTURER AS T3 ON T3.IDManufacturer = T1.IDManufacturer
WHERE
Manufacturer_Name  = 'Samsung') AS TB1
INNER JOIN DIM_LOCATION AS T4 ON T4.IDLocation = TB1.IDLocation
WHERE
Country = 'US'
ORDER BY 
SUM(Quantity) DESC


--Q3.
SELECT
State,
ZipCode,
Model_Name,
COUNT(IDCustomer) AS TRANSACTIONS
FROM 
(SELECT
IDCustomer,
T1.IDModel,
IDLocation,
Model_Name,
Quantity
FROM
FACT_TRANSACTIONS AS T1
INNER JOIN DIM_MODEL AS T2 ON T2.IDModel = T1.IDModel) AS TB1
INNER JOIN DIM_LOCATION AS T3 ON T3.IDLocation = TB1.IDLocation
GROUP BY 
State,
ZipCode,
Model_Name


--Q4.
SELECT TOP 1
Manufacturer_Name,
Model_Name,
Unit_price
FROM
DIM_MODEL AS T1
INNER JOIN DIM_MANUFACTURER AS T2 ON T2.IDManufacturer = T1.IDManufacturer
ORDER BY
Unit_price


--Q5.
SELECT TOP 5
Manufacturer_Name,
AVG(Unit_price) AS AVG_PRICE,
SUM(CAST(Quantity AS FLOAT)) AS SALES
FROM
DIM_MODEL AS T1
INNER JOIN DIM_MANUFACTURER AS T2 ON T2.IDManufacturer = T1.IDManufacturer
INNER JOIN FACT_TRANSACTIONS AS T3 ON T3.IDModel = T1.IDModel
GROUP BY
Manufacturer_Name,
Quantity 
ORDER BY
SUM(CAST(Quantity AS FLOAT)) DESC,
AVG(Unit_price) 


--Q6.
SELECT 
Customer_Name,
AVG(TotalPrice) AS AVG_SPENT
FROM 
FACT_TRANSACTIONS AS T1
INNER JOIN DIM_CUSTOMER AS T2 ON T2.IDCustomer = T1.IDCustomer
WHERE
DATE > '2008-12-31' AND DATE < '2010-01-01' 
GROUP BY
Customer_Name
HAVING
AVG(TotalPrice) > 500


--Q7.
SELECT Model_Name FROM
(SELECT * FROM
(SELECT ROW_NUMBER() OVER( PARTITION BY YEAR ORDER BY SUM(Quantity) DESC ) AS RNUM,Model_Name,SUM(Quantity) AS QTY_SOLD,YEAR
FROM
(SELECT Model_Name,Quantity,DATEPART(YEAR,Date) AS YEAR
FROM 
FACT_TRANSACTIONS AS T1 INNER JOIN DIM_MODEL AS T2 ON T2.IDModel = T1.IDModel) AS TB1
WHERE YEAR IN ('2008','2009','2010')
GROUP BY  Model_Name,YEAR) AS TB2
WHERE RNUM BETWEEN 1 AND 5) AS TB3
GROUP BY  Model_Name
HAVING COUNT(Model_Name)=3


--Q8.
SELECT * FROM
(SELECT ROW_NUMBER() OVER( PARTITION BY YEAR ORDER BY SUM(Quantity) DESC ) AS RNUM,Manufacturer_Name,SUM(Quantity) AS QTY_SOLD,YEAR
FROM
(SELECT
Manufacturer_Name,
Quantity,
DATEPART(YEAR,Date) AS YEAR
FROM 
DIM_MODEL  AS T1
INNER JOIN FACT_TRANSACTIONS AS T2 ON T2.IDModel=T1.IDModel
INNER JOIN DIM_MANUFACTURER AS T3 ON T3.IDManufacturer = T1.IDManufacturer) AS TB1
WHERE YEAR IN ('2009','2010')
GROUP BY  Manufacturer_Name,YEAR) AS TB2
WHERE RNUM = 2


--Q9.
SELECT Manufacturer_Name FROM
(SELECT ROW_NUMBER() OVER( PARTITION BY YEAR ORDER BY Manufacturer_Name ) AS RNUM,Manufacturer_Name,YEAR
FROM
(SELECT DISTINCT Manufacturer_Name, DATEPART(YEAR,Date) AS YEAR
FROM 
DIM_MODEL  AS T1
INNER JOIN FACT_TRANSACTIONS AS T2 ON T2.IDModel=T1.IDModel
INNER JOIN DIM_MANUFACTURER AS T3 ON T3.IDManufacturer = T1.IDManufacturer
WHERE DATEPART(YEAR,Date) IN ('2009','2010')) AS TB1) AS TB2
GROUP BY
Manufacturer_Name
HAVING
COUNT(Manufacturer_Name) = 1


--Q10.
SELECT *,
(SPEND_2004-SPEND_2003)*100/NULLIF(SPEND_2003,0) AS PRCNT_CHANGE2004,
(SPEND_2005-SPEND_2004)*100/NULLIF(SPEND_2004,0) AS PRCNT_CHANGE2005,
(SPEND_2006-SPEND_2005)*100/NULLIF(SPEND_2005,0) AS PRCNT_CHANGE2006,
(SPEND_2007-SPEND_2006)*100/NULLIF(SPEND_2006,0) AS PRCNT_CHANGE2007,
(SPEND_2008-SPEND_2007)*100/NULLIF(SPEND_2007,0) AS PRCNT_CHANGE2008,
(SPEND_2009-SPEND_2008)*100/NULLIF(SPEND_2008,0) AS PRCNT_CHANGE2009,
(SPEND_2010-SPEND_2009)*100/NULLIF(SPEND_2009,0) AS PRCNT_CHANGE2010
FROM
(SELECT 
Customer_Name,
AVG(CASE WHEN YEAR = 2003 THEN SPEND ELSE 0 END) AS SPEND_2003,
AVG(CASE WHEN YEAR = 2004 THEN SPEND ELSE 0 END) AS SPEND_2004,
AVG(CASE WHEN YEAR = 2005 THEN SPEND ELSE 0 END) AS SPEND_2005,
AVG(CASE WHEN YEAR = 2006 THEN SPEND ELSE 0 END) AS SPEND_2006,
AVG(CASE WHEN YEAR = 2007 THEN SPEND ELSE 0 END) AS SPEND_2007,
AVG(CASE WHEN YEAR = 2008 THEN SPEND ELSE 0 END) AS SPEND_2008,
AVG(CASE WHEN YEAR = 2009 THEN SPEND ELSE 0 END) AS SPEND_2009,
AVG(CASE WHEN YEAR = 2010 THEN SPEND ELSE 0 END) AS SPEND_2010
FROM
(SELECT * FROM
(SELECT 
ROW_NUMBER() OVER( PARTITION BY DATEPART(YEAR,Date) ORDER BY Customer_Name ) AS RNUM,
Customer_Name,
SUM(TotalPrice) AS SPEND,
SUM(Quantity) AS QTY,
DATEPART(YEAR,Date) AS YEAR
FROM 
FACT_TRANSACTIONS AS T1
INNER JOIN DIM_CUSTOMER AS T2 ON T2.IDCustomer = T1.IDCustomer
GROUP BY Customer_Name,DATEPART(YEAR,Date)) AS TB1
WHERE RNUM BETWEEN 1 AND 10) AS TB2
GROUP BY Customer_Name) AS TB3


